### ISSUE TITLE
When the code will release?

### ISSUE THREAD

**Issue by betterze** [genforce/insgen#1]
Dear Genforce group, 

Thank you for your great work of <Data-Efficient Instance Generation from Instance Discrimination>. I really like it.

When the code will release?

Thank you for your help.

Best Wishes,

Alex

**Comment by limbo0000** [comment]
Hi Alex, thanks for your interest in our work. Our code would be available in August or September. Stay tuned!

**Comment by betterze** [comment]
Thx.
